import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

export const data = [
  {
    month: 'Jul 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Aug 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Sep 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1,
  },
  {
    month: 'Oct 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Nov 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.2,
  },
  {
    month: 'Dec 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.3,
  },
  {
    month: 'Jan 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Feb 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.8,
  },
  {
    month: 'Mar 2020',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 2.1,
  },
  {
    month: 'Apr 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 2.8,
  },
  {
    month: 'May 2020',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.1,
  },
  {
    month: 'Jun 2020',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.6,
  },
  {
    month: 'Jul 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Aug 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Sep 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1,
  },
  {
    month: 'Oct 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Nov 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.2,
  },
  {
    month: 'Dec 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.3,
  },
  {
    month: 'Jan 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Feb 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.8,
  },
  {
    month: 'Mar 2021',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 2.1,
  },
  {
    month: 'Apr 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 2.8,
  },
  {
    month: 'May 2021',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.1,
  },
  {
    month: 'Jun 2021',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.6,
  },
  {
    month: 'Jul 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Aug 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 0.8,
  },
  {
    month: 'Sep 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1,
  },
  {
    month: 'Oct 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Nov 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.2,
  },
  {
    month: 'Dec 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.3,
  },
  {
    month: 'Jan 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.5,
  },
  {
    month: 'Feb 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 1.8,
  },
  {
    month: 'Mar 2022',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 2.1,
  },
  {
    month: 'Apr 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 1,
    restrictedWorkInjury: 1,
    benchmark: 25,
    TRIFR: 2.8,
  },
  {
    month: 'May 2022',
    lostTimeInjury: 1,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.1,
  },
  {
    month: 'Jun 2022',
    lostTimeInjury: 0,
    medicalTreatmentInjury: 0,
    restrictedWorkInjury: 0,
    benchmark: 25,
    TRIFR: 3.6,
  },
];

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
